version: '3.9'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - WEB_CONCURRENCY=1

    volumes:
      - ../../.:/usr/src/app/:cached
      - cloudrun_on_rails_bundle:/usr/local/bundle

volumes:
  cloudrun_on_rails_bundle:
